name: Build ve Yayınla

on:
  push:
    branches:
      - master  # Eğer senin ana dal main ise 'main' yaz

jobs:
  build-ve-yayinla:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16  # package.json'daki node versiyonuna göre

      - run: npm install

      - run: npm run build:bit  # build komutunu burada kullanıyoruz

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
